trigger:
  branches:
    include:
    - main
  paths:
    include:
    - '*.bicep'
    - '.pipelines/publish-modules.yaml'
    exclude:
    - '**/main.bicep' # only include modules
 
pr: none
 
variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  modulePrefix: 'bicep/modules/'
  registryName: cmhbicep
 
jobs:
- job: modules
  displayName: 'Publish Bicep Modules'
  condition: eq(variables.isMain, 'true')
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: AzureCLI@2
    displayName: 'Publish/Update Modules to Registry'
    inputs:
      azureSubscription: AIRS
      scriptType: 'pscore'
      scriptLocation: inlineScript
      inlineScript: |
        az bicep install
        az acr login -n $(registryName)
        $version = (Get-Date -f 'yyyy-MM-dd') + '.$(Build.BuidId)'
        $publishedModules = $(az acr repository list --name $(registryName) --query "[?contains(@, '$(modulePrefix)')]" -o tsv)
        Get-ChildItem -Recurse -Path ./modules/*.bicep | Foreach-Object {
          $filename = ($_ | Resolve-Path -Relative) -replace "^./" -replace '\..*'
          Write-Host "Checking existing mod $modulePrefix $fileName"
          # Check if module already exists in the registry
          If (-not ($publishedModules ?? @()).Contains(("bicep/" + $filename))) {
            Write-Host "Adding new module $filename with version $version"
            az bicep publish --file $_ --target br:$(registryName).azurecr.io/bicep/${filename}:${version}
            $onlyFileName = $fileName.replace("modules/", "")
            Write-Host "Marking module $onlyFileName`:$version read-only"
            $image = "bicep/modules/$onlyFileName`:$version"
            Write-Host "Image is $image"
            az acr repository update --name $(registryName) --image $image --write-enabled false
          }
        }
 
        git diff-tree --no-commit-id --name-only --diff-filter=ad -r -m $(Build.SourceVersion) | Where-Object {$_.EndsWith('.bicep')} | Foreach-Object {
          $moduleName = ($_ | Resolve-Path -Relative) -replace "^./" -replace '\..*'
          Write-Host "Updating existing module $moduleName with version $version"
          az bicep publish --file $_ --target br:$(registryName).azurecr.io/$(modulePrefix)${moduleName}:${version}
          Write-Host "Marking module $moduleName`:$version read-only"
          az acr repository update --name $(registryName) --image ${moduleName}:${version} --write-enabled false
        }